tsundoku/blueprints/ux/__init__.py
from .routes import ux_blueprint

__all__ = ["ux_blueprint"]

tsundoku/blueprints/ux/routes.py
from asyncio import Queue
from datetime import timedelta
from functools import wraps
from typing import TYPE_CHECKING, Any
from uuid import uuid4

from argon2 import PasswordHasher
from argon2.exceptions import VerifyMismatchError
from quart import Blueprint
from quart import Response as QuartResponse
from quart_rate_limiter import RateLimitExceeded, rate_limit
from werkzeug import Response

if TYPE_CHECKING:
    import tsundoku.app

    app = tsundoku.app.TsundokuApp()
else:
    from quart import current_app as app

from quart import (
    flash,
    redirect,
    render_template,
    request,
    send_file,
    url_for,
    websocket,
)
from quart_auth import (
    Unauthorized,
    current_user,
    login_required,
    login_user,
    logout_user,
)

from tsundoku import __version__ as version
from tsundoku.blueprints.api import APIResponse
from tsundoku.constants import DATA_DIR
from tsundoku.decorators import deny_readonly
from tsundoku.user import User

from .issues import get_issue_url

ux_blueprint = Blueprint(
    "ux",
    __name__,
    template_folder="templates",
    static_folder="static",
    static_url_path="/ux/static",
)
hasher = PasswordHasher()


@ux_blueprint.errorhandler(Unauthorized)
async def redirect_to_login(_: Any) -> Response:  # noqa: RUF029
    if app.flags.IS_FIRST_LAUNCH:
        return redirect(url_for("ux.register"))

    return redirect(url_for("ux.login"))


@ux_blueprint.errorhandler(429)
async def err_429(e: Exception) -> Response:
    error = "Too many requests."
    if isinstance(e, RateLimitExceeded):
        error += f" Try again in {e.retry_after} seconds."

    await flash(error, category="error")
    return redirect(request.url)


@ux_blueprint.context_processor
async def update_context() -> dict:  # noqa: RUF029
    fluent = app.get_fluent()
    stats = {"version": version}

    return {
        "stats": stats,
        "docker": app.flags.IS_DOCKER,
        "update_info": app.flags.UPDATE_INFO,
        "_": fluent.format_value,
    }


@ux_blueprint.route("/issue", methods=["POST"])
@login_required
@deny_readonly
async def issue() -> APIResponse:
    data = await request.get_json()

    issue_type = data.get("issue_type")
    user_agent = data.get("user_agent")

    return APIResponse(result=get_issue_url(issue_type, user_agent))


@ux_blueprint.route("/", methods=["GET"])
@ux_blueprint.route("/nyaa", methods=["GET"])
@ux_blueprint.route("/webhooks", methods=["GET"])
@ux_blueprint.route("/config", methods=["GET"])
@login_required
async def index() -> str:
    fluent = app.get_fluent()
    if app.flags.DL_CLIENT_CONNECTION_ERROR:
        await flash(fluent._("dl-client-connection-error"), category="error")

    return await render_template("index.html")


@ux_blueprint.route("/logs", methods=["GET"])
@login_required
async def logs() -> str | QuartResponse:
    if request.args.get("dl"):
        return await send_file(f"{DATA_DIR / 'tsundoku.log'}", as_attachment=True)

    fluent = app.get_fluent()
    if app.flags.DL_CLIENT_CONNECTION_ERROR:
        await flash(fluent._("dl-client-connection-error"), category="error")

    return await render_template("index.html")


@ux_blueprint.route("/register", methods=["GET", "POST"])
@deny_readonly
async def register() -> Any:
    if not app.flags.IS_FIRST_LAUNCH or await current_user.is_authenticated:
        return redirect("/")

    if request.method == "GET":
        return await render_template("register.html")
    fluent = app.get_fluent()
    form = await request.form

    username = form.get("username")
    password = form.get("password")
    password_confirm = form.get("confirmPassword")
    if not username:
        await flash(
            fluent._("form-register-missing-data", {"field": "username"}),
            category="error",
        )
        return redirect(url_for("ux.register"))
    if not password:
        await flash(
            fluent._("form-register-missing-data", {"field": "password"}),
            category="error",
        )
        return redirect(url_for("ux.register"))
    if len(password) < 8:
        await flash(fluent._("form-password-characters"), category="error")
        return redirect(url_for("ux.register"))
    if password != password_confirm:
        await flash(fluent._("form-password-mismatch"), category="error")
        return redirect(url_for("ux.register"))

    async with app.acquire_db() as con:
        existing_id = await con.fetchval(
            """
                SELECT
                    id
                FROM
                    users
                WHERE
                    LOWER(username) = LOWER(?);
            """,
            username,
        )

    # technically not possible to get to this page if there are
    # any other users at all
    if existing_id is not None:
        await flash(fluent._("form-username-taken"), category="error")
        return redirect(url_for("ux.register"))

    pw_hash = PasswordHasher().hash(password)
    async with app.acquire_db() as con:
        await con.execute(
            """
                INSERT INTO
                    users
                    (username, password_hash, api_key)
                VALUES
                    (?, ?, ?);
            """,
            username,
            pw_hash,
            str(uuid4()),
        )

    if app.flags.IS_FIRST_LAUNCH:
        app.flags.IS_FIRST_LAUNCH = False

    await flash(fluent._("form-register-success"), category="success")
    return redirect(url_for("ux.login"))


@ux_blueprint.route("/login", methods=["GET"])
async def login() -> Response | str:
    if await current_user.is_authenticated:
        return redirect("/")

    return await render_template("login.html")


@ux_blueprint.route("/login", methods=["POST"])
@rate_limit(1, timedelta(seconds=2))
@rate_limit(10, timedelta(minutes=1))
@rate_limit(20, timedelta(hours=1))
async def login_post() -> Any:
    if await current_user.is_authenticated:
        return redirect("/")

    fluent = app.get_fluent()
    form = await request.form

    username = form.get("username")
    password = form.get("password")
    if not username or not password:
        await flash(fluent._("form-missing-data"), category="error")
        return redirect(url_for("ux.login"))

    async with app.acquire_db() as con:
        user_data = await con.fetchone(
            """
            SELECT
                id,
                password_hash
            FROM
                users
            WHERE LOWER(username) = ?;
        """,
            username.lower(),
        )

    if not user_data:
        await flash(fluent._("invalid-credentials"), category="error")
        return redirect(url_for("ux.login"))

    try:
        hasher.verify(user_data["password_hash"], password)
    except VerifyMismatchError:
        await flash(fluent._("invalid-credentials"), category="error")
        return redirect(url_for("ux.login"))

    if hasher.check_needs_rehash(user_data["password_hash"]):
        async with app.acquire_db() as con:
            await con.execute(
                """
                UPDATE
                    users
                SET
                    password_hash=?
                WHERE username=?;
            """,
                hasher.hash(password),
                username,
            )

    remember = form.get("remember", False)

    login_user(User(user_data["id"]), remember=remember)

    return redirect("/")


@ux_blueprint.route("/logout", methods=["GET"])
@login_required
async def logout() -> Any:  # noqa: RUF029
    logout_user()
    return redirect("/")


def collect_websocket(func: Any) -> Any:
    @wraps(func)
    async def wrapper(*args: Any, **kwargs: Any) -> Any:
        queue = Queue()
        app.connected_websockets.add(queue)
        try:
            return await func(queue, *args, **kwargs)
        finally:
            app.connected_websockets.remove(queue)

    return wrapper


@ux_blueprint.websocket("/ws/logs")
@collect_websocket
async def logs_ws(queue: Queue[str]) -> None:
    await websocket.send("ACCEPT")
    while True:
        record = await queue.get()
        await websocket.send(record)

tsundoku/blueprints/ux/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Page Meta -->
    <meta charset="UTF-8" />
    <title>{{ _("page-title") }}</title>
    <link
      rel="shortcut icon"
      href="{{ url_for ('ux.static', filename='img/favicon.ico') }}"
    />

    <!-- CSS -->
    <link
      rel="stylesheet"
      href="{{ url_for('ux.static', filename='css/base.css') }}"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/@creativebulma/bulma-tooltip@1.0.2/dist/bulma-tooltip.min.css"
      integrity="sha384-EBGMr0LJD7tRVfxRKCHIGWo0kMW1fseE7eFCIZFyF/nzdZMxZ1/u6DBSuyrXdBCP"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
    />

    <script>
      window["LOCALE"] = "{{LOCALE}}";

      const theme = localStorage.getItem("theme");

      document.documentElement.style.backgroundColor =
        theme === "dark" ? "hsl(0deg, 0%, 21%)" : "#fff";

      const toggleTheme = () => {
        const isDark = document.body.classList.contains("dark");
        if (isDark) {
          document.body.classList.remove("dark");
          localStorage.setItem("theme", "light");
        } else {
          document.body.classList.add("dark");
          localStorage.setItem("theme", "dark");
        }
      };

      window.onload = () => {
        if (theme === "dark") {
          document.getElementById("darkModeSwitch").checked = true;
          document.body.classList.add("dark");
        }

        document.body.style.removeProperty("visibility");
        document.documentElement.style.removeProperty("background-color");

        setTimeout(() => {
          document.body.classList.add("do-theme-transition");
        }, 500);
      };
    </script>

    <!-- JS -->
    <script
      src="https://unpkg.com/bulma-modal-fx/dist/js/modal-fx.min.js"
      integrity="sha384-R+4Ivym139x+5G2a03CfiIp2ZInb03PRZcuibbrPsTpQ8DPaXeLZ71pzuLRyOFZN"
      crossorigin="anonymous"
    ></script>
    <script
      type="module"
      src="https://unpkg.com/ionicons@5.4.0/dist/ionicons/ionicons.esm.js"
    ></script>
    <script
      nomodule=""
      src="https://unpkg.com/ionicons@5.4.0/dist/ionicons/ionicons.js"
    ></script>

    {% block extralib %} {% endblock %}
  </head>

  <body style="visibility: hidden">
    <div class="dashboard is-full-height">
      <div class="dashboard-panel is-small">
        <header class="dashboard-panel-header">
          <div class="has-text-centered">
            <img
              src="{{ url_for('ux.static', filename='img/logo.png') }}"
              width="112"
              height="28"
            />
          </div>
        </header>

        <div class="dashboard-panel-content">
          <aside class="menu has-text-white">
            <p class="menu-label">{{ _("category-general") }}</p>
            <ul class="menu-list">
              <li>
                <a id="navIndex" href="/">{{ _("page-shows") }}</a>
              </li>
            </ul>
            <p class="menu-label">{{ _("category-settings") }}</p>
            <ul class="menu-list">
              <li>
                <a id="navWebhooks" href="/webhooks"
                  >{{ _("page-webhooks") }}</a
                >
              </li>
              <li>
                <a id="navConfig" href="/config">{{ _("page-config") }}</a>
              </li>
              <li>
                <a id="navLogs" href="/logs">{{ _("page-logs") }}</a>
              </li>
            </ul>
          </aside>
        </div>

        <div class="menu-panel-footer has-text-centered is-size-7">
          <div class="field">
            <input
              id="darkModeSwitch"
              type="checkbox"
              class="switch"
              onChange="toggleTheme();"
            />
            <label for="darkModeSwitch">Dark Mode</label>
          </div>

          <a href="{{ url_for('ux.logout') }}" class="button is-danger is-small"
            >{{ _("logout-button") }}</a
          >
          <p class="mt-4">
            Tsundoku v{{ stats.version }} {% if docker %}🐋{% endif %}
          </p>
          {% if update_info is not none %}
          <p class="has-text-success">
            New version available:
            <a href="{{ update_info.url }}">v{{ update_info.version }}</a>
          </p>
          {% endif %}
          <p>
            <b>Tsundoku</b> is an
            <a href="https://github.com/tylergibbs2/Tsundoku"
              >open-source project.</a
            >
          </p>
          <p>Copyright (c) 2020-2025 Tyler Gibbs</p>
        </div>
      </div>

      <div class="dashboard-main is-scrollable">
        {% block content %} {% endblock %}
      </div>
    </div>
  </body>

  {% block webpack %} {% endblock %}
</html>

tsundoku/blueprints/ux/templates/index.html
{% extends "base.html" %} {% block webpack %}
<script src="{{ url_for('ux.static', filename='js/root.js') }}"></script>
{% endblock %} {% block content %} {% include "messages.html" %}

<section id="root" class="section"></section>

{% endblock %}

tsundoku/blueprints/ux/templates/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Page Meta -->
    <meta charset="UTF-8" />
    <title>積ん読 ANIME</title>
    <link
      rel="shortcut icon"
      href="{{ url_for ('ux.static', filename='img/favicon.ico') }}"
    />

    <script>
      window["LOCALE"] = "{{LOCALE}}";
    </script>

    <!-- CSS -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.9.0/css/bulma.min.css"
      integrity="sha512-ADrqa2PY1TZtb/MoLZIZu/Z/LlPaWQeDMBV73EMwjGam43/JJ5fqW38Rq8LJOVGCDfrJeOMS3Q/wRUVzW5DkjQ=="
      crossorigin="anonymous"
    />
  </head>

  <body>
    <div class="container">
      <div class="container mt-3" style="width: 50%">
        {% include "messages.html" %}
      </div>
      <h1 class="title is-1 has-text-centered mt-6">Tsundoku</h1>
      <div class="columns is-centered mt-1">
        <div class="column is-one-third">
          <form class="box" action="{{ url_for('ux.login') }}" method="POST">
            <div class="field">
              <label class="label">{{ _("username") }}</label>
              <input
                class="input"
                type="text"
                name="username"
                placeholder="{{ _('username') }}"
                required
              />
            </div>

            <div class="field">
              <label class="label">{{ _("password") }}</label>
              <input
                class="input"
                type="password"
                name="password"
                placeholder="••••••••"
                required
              />
            </div>

            <div class="field">
              <label class="checkbox">
                <input name="remember" type="checkbox" />
                {{ _("remember-me") }}
              </label>
            </div>

            <div class="field has-text-centered">
              <div class="control">
                <button type="submit" class="button is-link">
                  {{ _("login-button") }}
                </button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </body>
</html>

tsundoku/blueprints/ux/templates/messages.html
{% with messages = get_flashed_messages(with_categories=true) %} {% if messages
%}
<script type="text/javascript">
  function deleteNotif() {
    document.querySelector(".notification").remove();
  }
</script>
{% for category, message in messages %}
<div
  class="notification {% if category == 'error' %}is-danger{% endif %}{% if category == 'success' %}is-success{% endif %} mx-6 mt-3"
>
  <button class="delete" onclick="deleteNotif();"></button>
  {{ message }}
</div>
{% endfor %} {% endif %} {% endwith %}

tsundoku/blueprints/ux/templates/modals/add_show_modal.html
<div id="add-show-modal" class="modal modal-fx-fadeInScale">
    <div class="modal-background" onclick="closeModals();"></div>
    <div class="modal-card">
        <header class="modal-card-head">
            <p class="modal-card-title">Add Show</p>
            <button class="delete" onclick="closeModals();" aria-label="close"></button>
        </header>

        <section class="modal-card-body">
            <form id="add-show-form" submit>
                <div class="field">
                    <label class="label">
                        <span class="has-tooltip-arrow has-tooltip-multiline has-tooltip-right"
                            data-tooltip="Name of the title as it appears in the RSS feed.">Name</span>
                    </label>
                    <div class="control">
                        <input name="title" class="input awesomplete" list="titles-datalist" type="text"
                            placeholder="Show title" required>
                        <datalist id="titles-datalist">
                            {% for title in seen_titles %}
                            <option>{{ title }}</option>
                            {% endfor %}
                        </datalist>
                    </div>
                </div>

                <div class="field">
                    <label class="label">
                        <span class="has-tooltip-arrow has-tooltip-multiline has-tooltip-right"
                            data-tooltip="Desired name of the file after it is renamed.">Desired Format</span>
                    </label>
                    <div class="control">
                        <input name="desired_format" class="input" type="text" placeholder="{n} - {s00e00}">
                    </div>
                </div>

                <div class="field">
                    <label class="label">
                        <span class="has-tooltip-arrow has-tooltip-multiline has-tooltip-right"
                            data-tooltip="Folder which to place the completed file.">Desired Folder</span>
                    </label>
                    <div class="control">
                        <input name="desired_folder" class="input" type="text">
                    </div>
                </div>

                <div class="field">
                    <label class="label">
                        <span class="has-tooltip-arrow has-tooltip-multiline has-tooltip-right"
                            data-tooltip="Value to use for the season of the series when renaming.">Season</span>
                    </label>
                    <div class="control">
                        <input name="season" class="input" type="number" value="1" required>
                    </div>
                </div>

                <div class="field">
                    <label class="label">
                        <span class="has-tooltip-arrow has-tooltip-multiline has-tooltip-right"
                            data-tooltip="Positive or negative value by which to modify the episode number as it appears in the RSS feed.">Episode
                            Offset</span>
                    </label>
                    <div class="control">
                        <input name="episode_offset" class="input" type="number" value="0" required>
                    </div>
                </div>
            </form>
        </section>

        <footer class="modal-card-foot is-size-7">
            <progress class="progress is-primary is-hidden is-small mt-2" max="100"></progress>
            <input class="button is-success submits-modals" type="submit" form="add-show-form" value="Add show"></button>
            <button class="button closes-modals" onclick="closeModals();">Cancel</button>
        </footer>
    </div>
</div>

tsundoku/blueprints/ux/templates/modals/delete_show_modal.html
<div id="delete-show-modal" class="modal modal-fx-fadeInScale">
    <div class="modal-background" onclick="closeModals();"></div>
    <div class="modal-card">
        <header class="modal-card-head">
            <p class="modal-card-title">Delete Show</p>
            <button class="delete" onclick="closeModals();" aria-label="close"></button>
        </header>

        <section class="modal-card-body">
            <p>Are you sure you want to delete <b><span id="item-to-delete-name"></span></b>?</p>
        </section>

        <footer class="modal-card-foot">
            <button id="delete-show-button" class="button is-danger">Delete</button>
            <button class="button" onclick="closeModals();">No, take me back</button>
        </footer>
    </div>
</div>

tsundoku/blueprints/ux/templates/modals/edit_show_modal.html
<div id="edit-show-modal" class="modal modal-fx-fadeInScale">
    <div class="modal-background" onclick="closeModals();"></div>
    <div class="modal-card">
        <header class="modal-card-head">
            <p class="modal-card-title">Edit Show</p>
            <div class="buttons">
                <button id="del-cache-btn" class="button is-warning">Clear Cache</button>
                <div id="fix-match-dropdown" class="dropdown is-right">
                    <div class="dropdown-trigger">
                        <button class="button is-link" onclick="toggleFixMatchDropdown();">
                            <span>Fix Match</span>
                        </button>
                    </div>
                    <div class="dropdown-menu" id="dropdown-menu2">
                        <div class="dropdown-content">
                            <div class="dropdown-item">
                                <p><strong>Kitsu.io Show ID</strong></p>
                            </div>
                            <div class="dropdown-item">
                                <input id="fix-match-input" type="number" min="0" class="input">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </header>

        <section class="modal-card-body">
            <div id="edit-control-tabs" class="tabs">
                <ul>
                    <li id="show-info-tab" class="is-active"><a onclick="displayShowInfo();">Information</a></li>
                    <li id="show-entry-tab"><a onclick="displayShowEntries();">Entries</a></li>
                    <li id="show-webhooks-tab"><a onclick="displayShowWebhooks();">Webhooks</a></li>
                </ul>
            </div>

            <div id="entry-tab-display" class="container is-hidden">
                <table id="show-entry-table" class="table is-fullwidth is-hoverable">
                    <caption id="entry-table-caption">Show Title</caption>
                    <thead>
                        <tr>
                            <th>Episode</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>

                <form id="add-show-entry-form" submit>
                    <div class="field is-horizontal">
                        <div class="field-body">
                            <div class="field-label is-normal">
                                <label class="label">Episode</label>
                            </div>
                            <div class="field">
                                <input name="episode" class="input" type="number" value="0" required>
                                <p class="help is-danger is-hidden">This episode is already tracked.</p>
                            </div>
                            <div class="field">
                                <input name="magnet" class="input" type="text" placeholder="Magnet URL">
                            </div>
                            <input type="hidden" name="show_id">
                            <input class="button is-success" type="submit" value="Add entry">
                        </div>
                    </div>
                </form>
            </div>

            <div id="webhook-tab-display" class="container is-hidden">
                
            </div>

            <form id="edit-show-form" submit>
                <div class="field">
                    <label class="label">
                        <span class="has-tooltip-arrow has-tooltip-multiline has-tooltip-right"
                            data-tooltip="Name of the title as it appears in the RSS feed.">Name</span>
                    </label>
                    <div class="control">
                        <input name="title" class="input" type="text" placeholder="Show title" required>
                    </div>
                </div>

                <div class="field">
                    <label class="label">
                        <span class="has-tooltip-arrow has-tooltip-multiline has-tooltip-right"
                            data-tooltip="Desired name of the file after it is renamed.">Desired Format</span>
                    </label>
                    <div class="control">
                        <input name="desired_format" class="input" type="text" placeholder="{n} - {s00e00}">
                    </div>
                </div>

                <div class="field">
                    <label class="label">
                        <span class="has-tooltip-arrow has-tooltip-multiline has-tooltip-right"
                            data-tooltip="Folder which to place the completed file.">Desired Folder</span>
                    </label>
                    <div class="control">
                        <input name="desired_folder" class="input" type="text">
                    </div>
                </div>

                <div class="field">
                    <label class="label">
                        <span class="has-tooltip-arrow has-tooltip-multiline has-tooltip-right"
                            data-tooltip="Value to use for the season of the series when renaming.">Season</span>
                    </label>
                    <div class="control">
                        <input name="season" class="input" type="number" value="1" required>
                    </div>
                </div>

                <div class="field">
                    <label class="label">
                        <span class="has-tooltip-arrow has-tooltip-multiline has-tooltip-right"
                            data-tooltip="Positive or negative value by which to modify the episode number as it appears in the RSS feed.">Episode
                            Offset</span>
                    </label>
                    <div class="control">
                        <input name="episode_offset" class="input" type="number" value="0" required>
                    </div>
                </div>

                <input name="kitsu_id" type="hidden">
            </form>
        </section>

        <footer class="modal-card-foot">
            <progress class="progress is-primary is-hidden is-small mt-2" max="100"></progress>
            <input class="button is-success submits-modals" type="submit" form="edit-show-form"
                value="Save changes"></button>
            <button class="button closes-modals" onclick="closeModals();">Cancel</button>
        </footer>
    </div>
</div>

tsundoku/blueprints/ux/templates/register.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Page Meta -->
    <meta charset="UTF-8" />
    <title>積ん読 ANIME</title>
    <link
      rel="shortcut icon"
      href="{{ url_for ('ux.static', filename='img/favicon.ico') }}"
    />

    <script>
      window["LOCALE"] = "{{LOCALE}}";
    </script>

    <!-- CSS -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.9.0/css/bulma.min.css"
      integrity="sha512-ADrqa2PY1TZtb/MoLZIZu/Z/LlPaWQeDMBV73EMwjGam43/JJ5fqW38Rq8LJOVGCDfrJeOMS3Q/wRUVzW5DkjQ=="
      crossorigin="anonymous"
    />
  </head>

  <body>
    <div class="container">
      <div class="container mt-3" style="width: 50%">
        {% include "messages.html" %}
      </div>
      <h1 class="title is-1 has-text-centered mt-6">Tsundoku</h1>
      <div class="columns is-centered mt-1">
        <div class="column is-one-third">
          <form class="box" action="{{ url_for('ux.register') }}" method="POST">
            <div class="field">
              <label class="label">{{ _("username") }}</label>
              <input
                class="input"
                type="text"
                name="username"
                placeholder="{{ _('username') }}"
                required
              />
            </div>

            <div class="field">
              <label class="label">{{ _("password") }}</label>
              <input
                class="input"
                type="password"
                name="password"
                placeholder="••••••••"
                required
              />
            </div>

            <div class="field">
              <label class="label">{{ _("confirm-password") }}</label>
              <input
                class="input"
                type="password"
                name="confirmPassword"
                placeholder="••••••••"
                required
              />
            </div>

            <div class="field has-text-centered">
              <div class="control">
                <button type="submit" class="button is-link">
                  {{ _("register-button") }}
                </button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </body>
</html>